"use client";

import { useRouter } from "next/router";
import { motion } from "framer-motion";
import {
  MapPin,
  Wand2,
  Landmark,
  Map as MapIcon,
  Languages,
  Mic,
  Luggage,
  Wallet,
  MessageCircle,
  ArrowDown,
  ArrowUpRight,
  Sparkles,
} from "lucide-react";

const fadeUp = {
  hidden: { opacity: 0, y: 56 },
  visible: { opacity: 1, y: 0 },
};

const features = [
  {
    icon: MapPin,
    title: "Search any PIN code in India",
    desc: "Real, live data for every district — not just a handful of demo cities. Powered by India Post + OpenTripMap.",
    color: "from-orange-300 to-pink-400",
  },
  {
    icon: Wand2,
    title: "AI Trip Planner",
    desc: "Tell it your destination, days, and budget — get a personalized day-by-day itinerary, generated by AI.",
    color: "from-fuchsia-300 to-rose-400",
  },
  {
    icon: Landmark,
    title: "AI Heritage Explorer",
    desc: "Upload a photo of a monument or statue — AI identifies it and tells you its story.",
    color: "from-violet-300 to-purple-400",
  },
  {
    icon: MapIcon,
    title: "Live interactive map",
    desc: "See hotels, homestays, and real nearby attractions plotted on a real map, for any city in India.",
    color: "from-cyan-300 to-sky-400",
  },
  {
    icon: MessageCircle,
    title: "AI Travel Companion",
    desc: "A floating chat assistant, available on every page, ready to answer any trip question.",
    color: "from-lime-300 to-emerald-400",
  },
  {
    icon: Mic,
    title: "Voice Negotiator",
    desc: "Speak naturally, get instant translation and polite negotiation help in 5 Indian languages.",
    color: "from-rose-300 to-pink-400",
  },
  {
    icon: Luggage,
    title: "AI Packing List",
    desc: "A personalized packing list based on your destination, trip length, and trip type.",
    color: "from-yellow-200 to-orange-400",
  },
  {
    icon: Wallet,
    title: "Budget Tracker",
    desc: "Track every rupee spent against your trip budget, broken down by category.",
    color: "from-emerald-300 to-teal-400",
  },
];

export default function Landing() {
  const router = useRouter();

  return (
    <div className="overflow-hidden bg-[#fff8f1] text-neutral-950">
      <section className="relative flex min-h-screen items-center justify-center overflow-hidden border-b-2 border-neutral-950 px-5 text-center sm:px-8">
        <img
          src="https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=2200&q=90"
          alt="Hawa Mahal in Jaipur"
          className="absolute inset-0 h-full w-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-black/25 via-black/50 to-black/80" />
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 32, repeat: Infinity, ease: "linear" }}
          className="pointer-events-none absolute -right-24 top-16 h-72 w-72 rounded-full border border-white/40 sm:h-96 sm:w-96"
        />
        <motion.div
          animate={{ scale: [1, 1.18, 1], opacity: [.35, .7, .35] }}
          transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }}
          className="pointer-events-none absolute -bottom-32 -left-20 h-96 w-96 rounded-full bg-fuchsia-500/40 blur-3xl"
        />

        <motion.div
          initial="hidden"
          animate="visible"
          variants={fadeUp}
          transition={{ duration: 0.85, ease: [0.16, 1, 0.3, 1] }}
          className="relative mx-auto w-full max-w-5xl px-1"
        >
          <span className="inline-flex items-center gap-2 rounded-full border border-white/40 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.17em] text-white backdrop-blur-md">
            <Sparkles className="h-3.5 w-3.5 text-yellow-300" /> AI-powered travel, made for India
          </span>
          <h1 className="tm-heading mt-7 text-5xl leading-[0.9] text-white drop-shadow-2xl sm:text-7xl md:text-8xl lg:text-[7rem]">
            Made for the
            <span className="block text-orange-300">unplanned.</span>
          </h1>
          <p className="mx-auto mt-7 max-w-2xl text-lg font-bold leading-relaxed text-white/85 sm:text-xl">
            TravelMitra puts every district, hidden gem, and wild idea in your pocket. Your India era starts here.
          </p>
          <div className="mt-14 flex flex-col items-center gap-2 text-white/90">
            <span className="text-xs font-black uppercase tracking-[0.17em]">Scroll to explore</span>
            <motion.span animate={{ y: [0, 8, 0] }} transition={{ repeat: Infinity, duration: 1.5 }}>
              <ArrowDown className="h-5 w-5" />
            </motion.span>
          </div>
        </motion.div>
      </section>

      <section className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8 md:py-32">
        <div className="absolute left-1/2 top-0 hidden h-full border-l-2 border-dashed border-neutral-950/20 lg:block" />
        <motion.h2
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.6 }}
          variants={fadeUp}
          transition={{ duration: 0.7 }}
          className="relative mx-auto max-w-3xl text-center tm-heading text-4xl leading-[.95] sm:text-6xl"
        >
          Big trip energy,<span className="block text-fuchsia-600">one smooth flow.</span>
        </motion.h2>

        <div className="relative mt-24 space-y-20 md:space-y-28">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, x: i % 2 === 1 ? 72 : -72, y: 28 }}
              whileInView={{ opacity: 1, x: 0, y: 0 }}
              viewport={{ once: true, amount: 0.4 }}
              transition={{ duration: 0.75, delay: 0.05, ease: [0.16, 1, 0.3, 1] }}
              className={`grid items-center gap-8 lg:grid-cols-2 lg:gap-20 ${
                i % 2 === 1 ? "lg:[&>*:first-child]:order-2" : ""
              }`}
            >
              <motion.div
                whileHover={{ rotate: i % 2 === 1 ? -2 : 2, y: -7 }}
                transition={{ type: "spring", stiffness: 300, damping: 18 }}
                className={`relative min-h-60 overflow-hidden rounded-[2rem] border-[3px] border-neutral-950 bg-gradient-to-br p-6 shadow-[9px_9px_0_0_#171717] sm:min-h-72 sm:p-9 ${f.color}`}
              >
                <div className="absolute -right-10 -top-10 h-44 w-44 rounded-full border-[3px] border-neutral-950/20 bg-white/40" />
                <div className="relative flex h-20 w-20 items-center justify-center rounded-[1.4rem] border-[3px] border-neutral-950 bg-white shadow-[5px_5px_0_0_#171717] sm:h-24 sm:w-24">
                  <f.icon className="h-9 w-9" strokeWidth={2.6} />
                </div>
                <div className="absolute bottom-5 left-5 rounded-xl border-2 border-neutral-950 bg-white px-3 py-1.5 text-xs font-black uppercase tracking-[.15em]">TravelMitra</div>
                <div className="absolute bottom-4 right-6 text-7xl font-black tracking-tighter text-neutral-950/20">0{i + 1}</div>
              </motion.div>
              <div className={i % 2 === 1 ? "lg:text-right" : ""}>
                <span className="text-sm font-black tracking-[0.15em] text-neutral-500">/0{i + 1}</span>
                <p className="mt-4 text-xs font-black uppercase tracking-[0.16em] text-fuchsia-700">{i === 0 ? "PIN-powered discovery" : i === 1 ? "Your itinerary, no tab chaos" : i === 2 ? "History, decoded" : i === 3 ? "See the whole scene" : i === 4 ? "Always-on travel brain" : i === 5 ? "Talk like a local" : i === 6 ? "Carry smarter" : "Spend with confidence"}</p>
                <h3 className="tm-heading mt-3 text-4xl leading-[.94] sm:text-5xl">
                  {f.title}
                </h3>
                <p className={`mt-5 max-w-lg text-base font-semibold leading-relaxed text-neutral-600 sm:text-lg ${i % 2 === 1 ? "lg:ml-auto" : ""}`}>
                  {f.desc}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      <section className="relative flex flex-col items-center justify-center gap-6 overflow-hidden border-t-2 border-neutral-950 bg-neutral-950 px-5 py-28 text-center text-white sm:px-8 md:py-36">
        <motion.div animate={{ x: [0, 40, 0], y: [0, -25, 0] }} transition={{ duration: 12, repeat: Infinity, ease: "easeInOut" }} className="absolute -left-20 top-8 h-72 w-72 rounded-full bg-orange-500 blur-[110px]" />
        <motion.div animate={{ x: [0, -45, 0], y: [0, 25, 0] }} transition={{ duration: 14, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-20 bottom-0 h-72 w-72 rounded-full bg-fuchsia-600 blur-[110px]" />
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.6 }}
          variants={fadeUp}
          transition={{ duration: 0.7 }}
          className="relative"
        >
          <p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Pack your curiosity</p>
          <h2 className="tm-heading mt-5 text-5xl leading-[.92] sm:text-7xl">
            Let&apos;s make stories.
          </h2>
          <p className="mx-auto mt-6 max-w-xl text-lg font-semibold leading-relaxed text-white/75">
            Bring a PIN code. We&apos;ll bring the local magic, the planning brain, and all the possibilities.
          </p>
          <motion.button
            onClick={() => router.push("/home")}
            whileHover={{ scale: 1.04, y: -4 }}
            whileTap={{ scale: .98 }}
            className="mt-10 inline-flex items-center gap-3 rounded-2xl border-[3px] border-white bg-orange-400 px-7 py-4 text-base font-black uppercase tracking-[0.1em] text-neutral-950 shadow-[7px_7px_0_0_#fff] transition-colors hover:bg-pink-400"
          >
            Get started <ArrowUpRight className="h-5 w-5" />
          </motion.button>
        </motion.div>
      </section>
    </div>
  );
}
